"""
Calibrate healthy residual statistics against the OPS simulator.

WHY THIS EXISTS
---------------
The nominal twin (Model 1) was trained on data/runs_v3, which was generated by
simulator/context.py's KinematicContextGenerator. Live inference under
server_ops runs against OpsEngineSim + OpsContextGenerator instead — a different
flight-dynamics model, with a PID autopilot and player-driven throttle, that
visits operating points the twin never saw. (Level flight held at 88% throttle
and labelled CRUISE, for instance: in training, CRUISE always meant 65-70%.)

The twin's error on those points is a systematic OFFSET, not noise. Measured on
a completely healthy ops flight, mean residual z ran -4 to -8 sigma across CHT,
MAP, fuel flow, oil temp and coolant — because the training-domain sigmas are
extremely tight (0.38 degC on CHT, 0.41 kPa on MAP), so two degrees of model
bias reads as five and a half sigma of "degradation".

Downstream that is catastrophic: compute_sensor_health_score penalises from
|mean_z| > 2, so a healthy climb reported cooling health 0.0 and the classifier
diagnosed lubrication_degradation+induction_loss on an engine with nothing
wrong with it.

Normalising residuals against statistics gathered on the same distribution you
infer over is the standard remedy. This script flies healthy ops missions across
the operating envelope, measures the residuals the twin actually produces there,
and writes per-phase and global (mean, std) per channel.

Nothing here retrains or modifies any model. It only measures what the existing
twin does on the deployment domain, so the z-scores fed to the classifier,
anomaly detector and health scorer are actually standardised.

USAGE
-----
    python calibrate_ops_residuals.py            # default 12 flights
    python calibrate_ops_residuals.py --flights 24

Output: ML/data/processed/residuals/healthy_residual_stats_ops.json
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

import numpy as np
import pandas as pd

from server_ops.ops_engine import OpsEngineSim
from pure_engine_ml import EngineHealthPipeline, CONTEXT_COLS, SENSOR_COLS

BASE = Path(__file__).parent
OUT_PATH = BASE / "ML/data/processed/residuals/healthy_residual_stats_ops.json"

DT = 0.05  # ops sim native step

# A residual std can never be usefully smaller than the channel's own
# measurement noise. Without a floor, a phase the sim happens to hold very
# steady (TAXI at fixed throttle) yields a near-zero std, and the next flight's
# ordinary noise then reads as tens of sigma. These are the per-channel noise
# amplitudes the simulator itself injects (simulator/thermal.py's
# CorrelatedNoiseEngine) plus its ADC quantisation step, so the floor is the
# instrument's real resolution rather than an arbitrary epsilon.
STD_FLOOR = {
    "rpm": 8.0, "vib_rms_g": 0.006, "map_kpa": 0.35, "fuel_flow_lph": 0.22,
    "fuel_press_bar": 0.02, "inj_timing_deg": 0.08, "bus_voltage_v": 0.05,
    "alt_current_a": 0.28, "oil_press_bar": 0.04, "oil_temp_c": 0.25,
    "coolant_temp_c": 0.25, "egt_1": 3.5, "egt_2": 3.5, "egt_3": 3.5, "egt_4": 3.5,
    "cht_1": 0.4, "cht_2": 0.4, "cht_3": 0.4, "cht_4": 0.4,
}

# Minimum samples before a phase gets its own calibration. A phase seen for a
# handful of seconds cannot support a trustworthy mean/std, and a bad per-phase
# figure is worse than falling back to the global one.
MIN_PHASE_SAMPLES = 120


def healthy_profiles(n: int) -> List[Dict[str, Any]]:
    """Healthy missions spanning the envelope the console actually flies.

    Deliberately varied in cruise altitude, cruise power and biome so the
    calibration reflects a range of operating points rather than one scripted
    sortie — otherwise it would simply memorise a single trajectory.
    """
    out: List[Dict[str, Any]] = []
    alts = [1500.0, 2500.0, 3000.0, 4000.0]
    cruise_powers = [62.0, 68.0, 72.0, 78.0]
    biomes = ["normal", "normal", "normal", "desert", "arctic"]
    for i in range(n):
        alt = alts[i % len(alts)]
        power = cruise_powers[(i // len(alts)) % len(cruise_powers)]
        out.append({
            "seed": 1000 + i * 17,
            "biome": biomes[i % len(biomes)],
            "target_alt": alt,
            "cruise_power": power,
        })
    return out


def fly_healthy(profile: Dict[str, Any], duration_s: float = 900.0) -> pd.DataFrame:
    """One healthy sortie. No faults are ever injected here — every residual
    this produces is by definition a twin modelling error, not degradation."""
    sim = OpsEngineSim(seed=int(profile["seed"]))
    target_alt = float(profile["target_alt"])
    cruise_power = float(profile["cruise_power"])

    schedule = [
        (0.0, {"throttle": 18.0, "gear": True, "autopilot": False, "biome": profile["biome"]}),
        (10.0, {"throttle": 95.0}),
        (28.0, {"throttle": 88.0, "autopilot": True, "ap_target_alt": target_alt, "gear": False}),
    ]
    rows: List[Dict[str, Any]] = []
    idx = 0
    levelled = False
    while sim.t_s < duration_s:
        while idx < len(schedule) and sim.t_s >= schedule[idx][0]:
            sim.set_player_input(schedule[idx][1])
            idx += 1
        # Pull back to cruise power once actually level, not at a fixed clock
        # time. Holding climb power in level flight is exactly the out-of-
        # distribution state this calibration exists to stop mattering, and it
        # should not be baked into the calibration set either.
        if not levelled and rows and rows[-1]["alt_m"] >= target_alt * 0.98:
            sim.set_player_input({"throttle": cruise_power})
            levelled = True
        rows.append(sim.step(dt=DT))

    df = pd.DataFrame(rows)
    df["sec"] = df["t_s"].astype(int)
    return df.groupby("sec").last().reset_index()  # 1 Hz, matching inference


def summarise(values: np.ndarray, channel: str) -> Dict[str, float]:
    """Robust centre and spread.

    Median and IQR-derived sigma rather than mean/std: a single transient (the
    thermal step right after a power change) would otherwise drag the centre of
    an entire phase and defeat the purpose.
    """
    if values.size == 0:
        return {"mean": 0.0, "std": 1.0, "n": 0}
    med = float(np.median(values))
    q1, q3 = np.percentile(values, [25, 75])
    iqr_sigma = float((q3 - q1) / 1.349) if q3 > q1 else 0.0
    # IQR-derived sigma only, floored. Folding in the raw standard deviation
    # would let the thermal transient right after a power change inflate the
    # spread for a whole phase, which is the opposite of robust.
    std = max(iqr_sigma, STD_FLOOR.get(channel, 1e-3))
    return {"mean": med, "std": std, "n": int(values.size)}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--flights", type=int, default=12)
    ap.add_argument("--duration", type=float, default=900.0)
    args = ap.parse_args()

    # Load the pipeline for its nominal twin only. Any previously written ops
    # calibration is irrelevant here: we are measuring the RAW twin residual.
    pipe = EngineHealthPipeline()

    per_phase: Dict[str, Dict[str, List[float]]] = {}
    per_global: Dict[str, List[float]] = {s: [] for s in SENSOR_COLS}

    profiles = healthy_profiles(args.flights)
    for i, prof in enumerate(profiles, 1):
        df = fly_healthy(prof, duration_s=args.duration)
        pred = pipe.predict_nominal_twin(df[CONTEXT_COLS])
        for s in SENSOR_COLS:
            res = df[s].to_numpy(dtype=np.float64) - pred[s].to_numpy(dtype=np.float64)
            per_global[s].extend(res.tolist())
            for ph in df["phase"].unique():
                mask = (df["phase"] == ph).to_numpy()
                per_phase.setdefault(str(ph), {}).setdefault(s, []).extend(res[mask].tolist())
        print(
            f"  flight {i:>2}/{len(profiles)}  seed={prof['seed']:<6} "
            f"biome={prof['biome']:<7} alt={prof['target_alt']:.0f}m "
            f"cruise={prof['cruise_power']:.0f}%  rows={len(df)}",
            flush=True,
        )

    sensor_stats = {s: summarise(np.asarray(per_global[s]), s) for s in SENSOR_COLS}

    by_phase: Dict[str, Dict[str, Dict[str, float]]] = {}
    for ph, chans in per_phase.items():
        n = max((len(v) for v in chans.values()), default=0)
        if n < MIN_PHASE_SAMPLES:
            print(f"  skipping phase {ph}: only {n} samples (< {MIN_PHASE_SAMPLES})")
            continue
        by_phase[ph] = {s: summarise(np.asarray(chans.get(s, [])), s) for s in SENSOR_COLS}

    payload = {
        "created_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "domain": "server_ops OpsEngineSim + OpsContextGenerator",
        "note": (
            "Healthy-only residual calibration for the OPS deployment domain. The twin "
            "is trained on data/runs_v3 (KinematicContextGenerator); these figures "
            "measure its systematic error on the ops flight model so residual z-scores "
            "are actually standardised at inference. Regenerate with "
            "calibrate_ops_residuals.py whenever the ops flight dynamics or the nominal "
            "twin change."
        ),
        "n_flights": len(profiles),
        "duration_s": args.duration,
        "sensor_stats": sensor_stats,
        "sensor_stats_by_phase": by_phase,
    }
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    print(f"\nwrote {OUT_PATH}")
    print(f"phases calibrated: {', '.join(sorted(by_phase)) or '(none)'}")
    print(f"\n{'channel':<16}{'global mean':>13}{'global std':>12}   (training std for comparison)")
    for s in SENSOR_COLS:
        old = pipe.healthy_stats.get(s, {}).get("std", float("nan"))
        st = sensor_stats[s]
        print(f"{s:<16}{st['mean']:>13.3f}{st['std']:>12.3f}   {old:>10.4f}")


if __name__ == "__main__":
    main()
