"""
The fault catalog: every fault the console can inject, defined once.

Engine faults move a physical health factor (physics.HF_NAMES), which is what the
twin estimates. Sensor faults corrupt one channel's reading and leave the engine
alone, which is what M1 has to tell apart from an engine fault.

Severity semantics (0..1):
  engine fault  factor target = healthy + severity * (failure threshold - healthy);
                severity 1.0 puts the factor exactly at its failure threshold.
  sensor fault  scales `magnitude` (bias / drift / spike); frozen and dropout ignore it.

`python -m twin2.catalog` regenerates contract/faults.json and server/contract/faults.json
from this file. The stub fallback in server/src/twin/stubTwin.ts replays each engine
fault as a per-channel cascade; those cascades are computed here from the same physics
at a reference cruise point, so the stub and the real simulator agree on direction and
rough size.
"""

import json
from typing import Dict, List, Optional

import numpy as np

from . import REPO
from .physics import FIT_CHANNELS, HF_FAIL, HF_HEALTHY, HF_NAMES, apply_health, nominal_targets

ENGINE_FAULT_RAMP_S = 30.0  # simulated seconds for a live engine fault to reach its target severity
CONTRACT_VERSION = "3.0.0"

ENGINE_FAULTS: Dict[str, dict] = {
    "turbo_degradation": {
        "label": "Turbocharger degradation", "factor": "eta_turbo", "subsystems": ["induction"]},
    "induction_leak": {
        "label": "Induction leak", "factor": "ve", "subsystems": ["induction", "fuel"]},
    "coolant_restriction": {
        "label": "Coolant circuit restriction", "factor": "cool_eff", "subsystems": ["cooling"]},
    "oil_restriction": {
        "label": "Oil circuit restriction", "factor": "oil_res", "subsystems": ["lubrication"]},
}
for _c in range(1, 5):
    ENGINE_FAULTS[f"weak_cylinder_cyl{_c}"] = {
        "label": f"Weak cylinder {_c}", "factor": f"comb_{_c}", "subsystems": ["combustion", "mechanical"],
        "cylinder": _c}

SENSOR_FAULTS: Dict[str, dict] = {
    "sensor_drift_egt2": {
        "label": "EGT 2 thermocouple drift", "channel": "egt_2", "mode": "drift",
        "magnitude": 90.0, "rampSec": 600.0},
    "sensor_frozen_coolant": {
        "label": "Coolant probe frozen", "channel": "coolant_temp_c", "mode": "frozen"},
    "sensor_bias_oilpress": {
        "label": "Oil pressure transducer bias", "channel": "oil_press_bar", "mode": "bias",
        "magnitude": -0.9},
    "sensor_dropout_map": {
        "label": "MAP sensor dropout", "channel": "map_kpa", "mode": "dropout"},
    "sensor_spike_egt4": {
        "label": "EGT 4 intermittent spikes", "channel": "egt_4", "mode": "spike", "magnitude": 80.0},
}


def target_theta(fault_id: str, severity: float) -> Optional[tuple]:
    """(factor index, target value) for an engine fault, None for a sensor fault."""
    spec = ENGINE_FAULTS.get(fault_id)
    if spec is None:
        return None
    i = HF_NAMES.index(spec["factor"])
    s = float(np.clip(severity, 0.0, 1.0))
    return i, float(HF_HEALTHY[i] + s * (HF_FAIL[i] - HF_HEALTHY[i]))


def _cruise_cascade(fault_id: str) -> List[dict]:
    """Per-channel change at full severity, at a reference cruise point (68% power, 3000 m, ISA)."""
    thr, alt, oat, ias = np.array([68.0]), np.array([3000.0]), np.array([0.5]), np.array([90.0])
    phase = np.array(["CRUISE"])
    nom = nominal_targets(thr, alt, oat, ias, phase)
    theta = HF_HEALTHY.copy()
    i, v = target_theta(fault_id, 1.0)  # type: ignore[misc]
    theta[i] = v
    deg = apply_health(nom, thr, theta)
    steps = []
    for ch in FIT_CHANNELS:
        d = float(deg[ch][0] - nom[ch][0])
        if abs(d) > 1e-6:
            steps.append({"channel": ch, "delaySec": 0, "rampSec": ENGINE_FAULT_RAMP_S,
                          "delta": round(d, 4), "shape": "linear"})
    return steps


def contract_json() -> dict:
    classes = [{"id": "healthy", "label": "Healthy", "subsystems": []}]
    for fid, spec in ENGINE_FAULTS.items():
        c = {"id": fid, "label": spec["label"], "subsystems": spec["subsystems"],
             "factor": spec["factor"], "cascade": _cruise_cascade(fid)}
        if "cylinder" in spec:
            c["cylinder"] = spec["cylinder"]
        classes.append(c)
    sensors = []
    for fid, spec in SENSOR_FAULTS.items():
        s = {"id": fid, "label": spec["label"], "channel": spec["channel"], "mode": spec["mode"]}
        if "magnitude" in spec:
            s["delta"] = spec["magnitude"]
        s["rampSec"] = spec.get("rampSec", 1.0)
        s["delaySec"] = 0
        sensors.append(s)
    return {
        "_source": "GENERATED by `python -m twin2.catalog` from twin2/catalog.py - do not edit by hand.",
        "_note": ("Engine faults degrade one physical health factor (twin2/physics.py). Cascades are that "
                  "factor's effect at full severity at a 68%-power cruise point, for the stub fallback only; "
                  "the real simulator applies the physics at every operating point."),
        "contract_version": CONTRACT_VERSION,
        "engineFaultRampSec": ENGINE_FAULT_RAMP_S,
        "classes": classes,
        "sensorFaults": sensors,
    }


def web_json() -> dict:
    """The console's fault menu: ids, labels and grouping only."""
    engine = [{"id": fid, "label": spec["label"], "cylinder": spec.get("cylinder")}
              for fid, spec in ENGINE_FAULTS.items()]
    sensor = [{"id": fid, "label": spec["label"], "channel": spec["channel"], "mode": spec["mode"]}
              for fid, spec in SENSOR_FAULTS.items()]
    return {"_source": "GENERATED by `python -m twin2.catalog` - do not edit by hand.",
            "engineFaultRampSec": ENGINE_FAULT_RAMP_S, "engine": engine, "sensor": sensor}


def write_contracts() -> List[str]:
    data = json.dumps(contract_json(), indent=2) + "\n"
    out = []
    for p in (REPO / "contract" / "faults.json", REPO / "server" / "contract" / "faults.json"):
        p.write_text(data, encoding="utf-8")
        out.append(str(p))
    web = REPO / "web" / "lib" / "faults.json"
    web.write_text(json.dumps(web_json(), indent=2) + "\n", encoding="utf-8")
    out.append(str(web))
    return out


if __name__ == "__main__":
    for p in write_contracts():
        print("wrote", p)
